build-job:
  stage: build
  script:
    - docker build --file /home/ubuntu/git/lims2-webapp-dockerfiles/low-level --tag sci/lims2:bionic /home/ubuntu/git/
    - docker build --file /home/ubuntu/git/lims2-webapp-dockerfiles/high-level --tag sci/lims2:fs --no-cache /home/ubuntu/git/
    - docker build --file /home/ubuntu/git/lims2-webapp-dockerfiles/test --tag sci/lims2:test /home/ubuntu/git/
test-job:
  stage: test
  script:
    - docker stop lims2_test || true && docker rm lims2_test || true
    - docker run
      --mount "type=bind,source=/home/ubuntu/lims2-webapp-shared,target=/shared"
      --mount "type=volume,source=bwa_genomes,destination=/home/user/bwa_genomes,readonly"
      --mount "type=bind,source=$CI_PROJECT_DIR,destination=/home/user/git_checkout/LIMS2-WebApp"
      --name lims2_test
      sci/lims2:test
