build-job:
  stage: build
  script:
    - cp -R /home/ubuntu/git/lims2-webapp-filesystem .
    - docker build --file dockerfiles/low-level --tag sci/lims2:bionic .
    - docker build --file dockerfiles/high-level --build-arg solr_url=$SOLR_URL --tag sci/lims2:fs --no-cache .
    - docker build --file dockerfiles/test --tag sci/lims2:test .
test-job:
  stage: test
  script:
    - docker stop lims2_test || true && docker rm lims2_test || true
    - docker run
      --mount "type=bind,source=/home/ubuntu/lims2-webapp-shared,target=/shared"
      --name lims2_test
      sci/lims2:test
