---
abstract: 'Catalyst based application'
author:
  - 'Wellcome Trust Sanger Institute'
build_requires:
  English: 0
  File::Find: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  IO::Scalar: 0
  LIMS2::Report::EPSummary: 0
  LIMS2::Report::ElectroporationProductionSummary: 0
  LIMS2::Report::FirstElectroporationProductionDetail: 0
  LIMS2::Report::GenesToElectroporate: 0
  LIMS2::Report::SecondElectroporationProductionDetail: 0
  LIMS2::Report::SponsorProgress: 0
  LIMS2::Report::VectorProductionDetail: 0
  LIMS2::Report::VectorProductionSummary: 0
  LIMS2::ReportGenerator::ProductionDetail: 0
  LIMS2::WebApp::Controller::User::SummaryReports: 0
  Test::Class: 0
  Test::More: 0.88
  Test::Most: 0
  YAML: 0
  bytes: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LIMS2-WebApp
requires:
  Bio::Perl: 0
  Bio::SCF: 0
  Bio::Seq: 0
  Bio::SeqIO: 0
  CHI: 0
  Carp: 0
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Controller::REST: 0
  Catalyst::Devel: 0
  Catalyst::Model::Adaptor: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Model::Factory::PerRequest: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80
  Catalyst::Script::FastCGI: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Class::Data::Inheritable: 0
  Config::Any: 0
  Config::Tiny: 0
  Const::Fast: 0
  Crypt::CBC: 0
  Crypt::SaltedHash: 0
  DBIx::Class::Core: 0
  DBIx::Class::ResultSet: 0
  DBIx::Class::Schema: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Connector: 0
  DBIx::RunSQL: 0
  DDP: 0
  Data::Compare: 0
  Data::Dump: 0
  Data::Dumper: 0
  Data::Pageset: 0
  Data::Printer: 0
  Data::UUID: 0
  Date::Calc: 0
  Date::Parse: 0
  DateTime: 0
  DateTime::Duration: 0
  DateTime::Format::ISO8601: 0
  DateTime::Format::Pg: 0
  DesignCreate::Util::BWA: 0
  DesignCreate::Util::Primer3: 0
  Digest::MD5: 0
  EngSeqBuilder: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  File::Temp: 0
  File::Which: 0
  File::stat: 0
  FindBin: 0
  Getopt::Long: 0
  GraphViz2: 0
  HTGT::QC::Config: 0
  HTGT::QC::Util::Alignment: 0
  HTGT::QC::Util::CigarParser: 0
  HTGT::QC::Util::CreateSuggestedQcPlateMap: 0
  HTGT::QC::Util::CrisprDamageVEP: 0
  HTGT::QC::Util::KillQCFarmJobs: 0
  HTGT::QC::Util::ListLatestRuns: 0
  HTTP::Status: 0
  Hash::Merge: 0
  Hash::MoreUtils: 0
  IO::Compress::Gzip: 0
  IO::File: 0
  IO::Pipe: 0
  IO::String: 0
  IPC::Run: 0
  Iterator::Simple: 0
  JSON: 0
  LIMS2::Exception: 0
  LIMS2::Exception::Database: 0
  LIMS2::Exception::Implementation: 0
  LIMS2::Exception::InvalidState: 0
  LIMS2::Exception::NotFound: 0
  LIMS2::Exception::System: 0
  LIMS2::Exception::Validation: 0
  LIMS2::REST::Client: 0
  LIMS2::Util: 0
  LIMS2::Util::ESQCUpdateWellAccepted: 0
  LIMS2::Util::EnsEMBL: 0
  LIMS2::Util::Errbit: 0
  LIMS2::Util::QcPrimers: 0
  LIMS2::Util::Solr: 0
  LIMS2::Util::Tarmits: 0
  LIMS2::Util::TraceServer: 0
  LIMS2::Util::WGE: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Log4perl: 0
  Log::Log4perl::Catalyst: 0
  Log::Log4perl::Level: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
  MooseX::Log::Log4perl: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  MooseX::Types: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Path::Class::MoreCoercions: 0
  Parse::BooleanLogic: 0
  Path::Class: 0
  Perl6::Slurp: 0
  Pod::Usage: 0
  Readonly: 0
  Scalar::Util: 0
  Spreadsheet::XLSX: 0
  Sub::Exporter: 0
  Template::AutoFilter: 0
  Term::ReadPassword: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  Text::CSV: 0
  Text::CSV_XS: 0
  Text::Iconv: 0
  Time::HiRes: 0
  Try::Tiny: 0
  TryCatch: 0
  URI: 0
  URI::QueryParam: 0
  WebAppCommon::Crispr::SubmitInterface: 0
  WebAppCommon::Design::CreateInterface: 0
  WebAppCommon::FormValidator: 0
  WebAppCommon::FormValidator::Constraint: 0
  WebAppCommon::Util::EnsEMBL: 0
  WebAppCommon::Util::FarmJobRunner: 0
  WebAppCommon::Util::FindGene: 0
  YAML::Any: 0
  YAML::XS: 0
  base: 0
  feature: 0
  namespace::autoclean: 0
  overload: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.315
