INSERT INTO schema_versions(version) VALUES (138);
INSERT INTO plate_types (id, description) VALUES ('EP_PIPELINE_II', 'EP plate for Pipeline II');
INSERT INTO process_types (id, description) VALUES ('ep_pipeline_ii', 'Create EP plate for pipeline II');
INSERT INTO nucleases(id, name) VALUES(7, 'SpCas9 WT protein Feldan');
INSERT INTO nucleases(id, name) VALUES(8, 'SpCas9 HiFi protein IDT');
INSERT INTO nucleases(id, name) VALUES(9, 'SpCas9n D10A protein IDT');
INSERT INTO nucleases(id, name) VALUES(10, 'eSpCas9_1.1 protein Sanger');
INSERT INTO nucleases(id, name) VALUES(11, 'SpCas9 VRQR protein Sanger');
INSERT INTO nucleases(id, name) VALUES(12, 'SpCas9 Protein Toolgen');
UPDATE nucleases SET name = 'SpCas9 WT plasmid Church' WHERE id = 5;
UPDATE nucleases SET name = 'SpCas9 D10A plasmid ZF (-bsd)' WHERE id = 4;
UPDATE nucleases SET name = 'SpCas9 H840A plasmid ZF (-bsd)' WHERE id = 3;
UPDATE nucleases SET name = 'SpCas9 WT plasmid ZF' WHERE id = 2;
UPDATE nucleases SET name = 'SpCas9 D10A plasmid Church (+bsd)' WHERE id = 1;
INSERT INTO guided_types(id, name) VALUES(1, 'crRNA/tracrRNA IDT');
INSERT INTO guided_types(id, name) VALUES(2, 'crRNA/tracrRNA Sigma');
INSERT INTO guided_types(id, name) VALUES(3, 'crRNA/tracrRNA GE');
INSERT INTO guided_types(id, name) VALUES(4, 'sgRNA Synthego');
INSERT INTO guided_types(id, name) VALUES(5, 'sgRNA IVT');
