CREATE TABLE nucleases (
       id integer NOT NULL,
       name TEXT NOT NULL,
       PRIMARY KEY(id)
);

CREATE TABLE process_nuclease (
       process_id integer NOT NULL REFERENCES processes(id),
       nuclease_id integer NOT NULL REFERENCES nucleases(id),
       PRIMARY KEY(process_id)
);
-- Drop the indices
DROP INDEX summaries_design_gene_id_index;
DROP INDEX summaries_design_gene_symbol_index;
DROP INDEX summaries_design_well_id_index;
DROP INDEX summaries_ep_pick_well_id_index;
DROP INDEX summaries_sep_pick_well_id_index;

-- Drop the primary key
ALTER TABLE public.summaries DROP CONSTRAINT IF EXISTS summaries_pkey CASCADE;

-- Rename current summaries table
ALTER TABLE public.summaries RENAME TO summaries_old;

-- Rename current sequence
ALTER SEQUENCE public.summaries_id_seq RENAME TO summaries_id_seq_old;

-- Create the new version of the summaries table
CREATE TABLE public.summaries (
    id serial unique primary key,
    insert_timestamp timestamp without time zone,
    design_id integer,
    design_name text,
    design_type text,
    design_species_id text,
    design_gene_id text,
    design_gene_symbol text,
    design_bacs text,
    design_phase integer,
    design_plate_name text,
    design_plate_id integer,
    design_well_name text,
    design_well_id integer,
    design_well_created_ts timestamp without time zone,
    design_well_assay_complete timestamp without time zone,
    design_well_accepted boolean,
    int_plate_name text,
    int_plate_id integer,
    int_well_name text,
    int_well_id integer,
    int_well_created_ts timestamp without time zone,
    int_recombinase_id text,
    int_qc_seq_pass boolean,
    int_cassette_name text,
    int_cassette_cre boolean,
    int_cassette_promoter boolean,
    int_cassette_conditional boolean,
    int_cassette_resistance text,
    int_backbone_name text,
    int_well_assay_complete timestamp without time zone,
    int_well_accepted boolean,
    final_plate_name text,
    final_plate_id integer,
    final_well_name name,
    final_well_id integer,
    final_well_created_ts timestamp without time zone,
    final_recombinase_id text,
    final_qc_seq_pass boolean,
    final_cassette_name text,
    final_cassette_cre boolean,
    final_cassette_promoter boolean,
    final_cassette_conditional boolean,
    final_cassette_resistance text,
    final_backbone_name text,
    final_well_assay_complete timestamp without time zone,
    final_well_accepted boolean,
    final_pick_plate_name text,
    final_pick_plate_id integer,
    final_pick_well_name name,
    final_pick_well_id integer,
    final_pick_well_created_ts timestamp without time zone,
    final_pick_recombinase_id text,
    final_pick_qc_seq_pass boolean,
    final_pick_cassette_name text,
    final_pick_cassette_cre boolean,
    final_pick_cassette_promoter boolean,
    final_pick_cassette_conditional boolean,
    final_pick_cassette_resistance text,
    final_pick_backbone_name text,
    final_pick_well_assay_complete timestamp without time zone,
    final_pick_well_accepted boolean,   
    dna_plate_name text,
    dna_plate_id integer,
    dna_well_name text,
    dna_well_id integer,
    dna_well_created_ts timestamp without time zone,
    dna_qc_seq_pass boolean,
    dna_status_pass boolean,
    dna_quality text,
    dna_quality_comment text,
    dna_well_assay_complete timestamp without time zone,
    dna_well_accepted boolean,
--New ASSEMBLY well info
    assembly_well_id integer,
    assembly_well_name text,
    assembly_plate_id integer,
    assembly_plate_name text,
    assembly_well_assay_complete timestamp without time zone,
    assembly_well_created_ts timestamp without time zone,
    assembly_well_accepted boolean,
    assembly_well_left_crispr_well_id integer,
    assembly_well_right_crispr_well_id integer,
--New CRISPR_EP well info
    crispr_ep_well_id integer,
    crispr_ep_well_name text,
    crispr_ep_plate_id integer,
    crispr_ep_plate_name text,
    crispr_ep_well_assay_complete timestamp without time zone,
    crispr_ep_well_created_ts timestamp without time zone,
    crispr_ep_well_accepted boolean,
    crispr_ep_well_nuclease text,
    crispr_ep_well_cell_line text,
--
    ep_plate_name text,
    ep_plate_id integer,
    ep_well_name text,
    ep_well_id integer,
    ep_well_created_ts timestamp without time zone,
    ep_well_recombinase_id text,
    ep_first_cell_line_name text,
    ep_colonies_picked integer,
    ep_colonies_total integer,
    ep_colonies_rem_unstained integer,
    ep_well_assay_complete timestamp without time zone,
    ep_well_accepted boolean,
    ep_pick_plate_name text,
    ep_pick_plate_id integer,
    ep_pick_well_name text,
    ep_pick_well_id integer,
    ep_pick_well_created_ts timestamp without time zone,
    ep_pick_well_recombinase_id text,
    ep_pick_qc_seq_pass boolean,
    ep_pick_well_assay_complete timestamp without time zone,
    ep_pick_well_accepted boolean,
    xep_plate_name text,
    xep_plate_id integer,
    xep_well_name text,
    xep_well_id integer,
    xep_well_created_ts timestamp without time zone,
    xep_well_recombinase_id text,
    xep_qc_seq_pass boolean,
    xep_well_assay_complete timestamp without time zone,
    xep_well_accepted boolean,
    sep_plate_name text,
    sep_plate_id integer,
    sep_well_name text,
    sep_well_id integer,
    sep_well_created_ts timestamp without time zone,
    sep_well_recombinase_id text,
    sep_well_assay_complete timestamp without time zone,
    sep_well_accepted boolean,
    sep_pick_plate_name text,
    sep_pick_plate_id integer,
    sep_pick_well_name text,
    sep_pick_well_id integer,
    sep_pick_well_created_ts timestamp without time zone,
    sep_pick_well_recombinase_id text,
    sep_pick_qc_seq_pass boolean,
    sep_pick_well_assay_complete timestamp without time zone,
    sep_pick_well_accepted boolean,
    fp_plate_name text,
    fp_plate_id integer,
    fp_well_name text,
    fp_well_id integer,
    fp_well_created_ts timestamp without time zone,
    fp_well_assay_complete timestamp without time zone,
    fp_well_accepted boolean,
    piq_plate_name text,
    piq_plate_id integer,
    piq_well_name text,
    piq_well_id integer,
    piq_well_created_ts timestamp without time zone,
    piq_well_assay_complete timestamp without time zone,
    piq_well_accepted boolean,
    sfp_plate_name text,
    sfp_plate_id integer,
    sfp_well_name text,
    sfp_well_id integer,
    sfp_well_created_ts timestamp without time zone,
    sfp_well_assay_complete timestamp without time zone,
    sfp_well_accepted boolean
);

-- Create table should have created the implicit summaries_pkey unique index, and the summaries_id_seq sequence
-- The new sequence will restart at 1, no reason to keep old sequence as no connected audits on this table

-- Create the indices

--
-- Name: summaries_design_gene_id_index; Type: INDEX; Schema: public; Owner: lims2; Tablespace: 
--

CREATE INDEX summaries_design_gene_id_index ON summaries USING btree (design_gene_id);


--
-- Name: summaries_design_gene_symbol_index; Type: INDEX; Schema: public; Owner: lims2; Tablespace: 
--

CREATE INDEX summaries_design_gene_symbol_index ON summaries USING btree (design_gene_symbol);


--
-- Name: summaries_design_well_id_index; Type: INDEX; Schema: public; Owner: lims2; Tablespace: 
--

CREATE INDEX summaries_design_well_id_index ON summaries USING btree (design_well_id);


--
-- Name: summaries_ep_pick_well_id_index; Type: INDEX; Schema: public; Owner: lims2; Tablespace: 
--

CREATE INDEX summaries_ep_pick_well_id_index ON summaries USING btree (ep_pick_well_id);


--
-- Name: summaries_sep_pick_well_id_index; Type: INDEX; Schema: public; Owner: lims2; Tablespace: 
--

CREATE INDEX summaries_sep_pick_well_id_index ON summaries USING btree (sep_pick_well_id);

-- Copy across the data from the old table into the new table
INSERT INTO summaries (
    -- leave id off the list so the serial key gets generated afresh
    insert_timestamp,
    design_id,
    design_name,
    design_type,
    design_species_id,
    design_gene_id,
    design_gene_symbol,
    design_bacs,
    design_phase,
    design_plate_name,
    design_plate_id,
    design_well_name,
    design_well_id,
    design_well_created_ts,
    design_well_assay_complete,
    design_well_accepted,
    int_plate_name,
    int_plate_id,
    int_well_name,
    int_well_id,
    int_well_created_ts,
    int_recombinase_id,
    int_qc_seq_pass,
    int_cassette_name,
    int_cassette_cre,
    int_cassette_promoter,
    int_cassette_conditional,
    int_cassette_resistance,
    int_backbone_name,
    int_well_assay_complete,
    int_well_accepted,
    final_plate_name,
    final_plate_id,
    final_well_name,
    final_well_id,
    final_well_created_ts,
    final_recombinase_id,
    final_qc_seq_pass,
    final_cassette_name,
    final_cassette_cre,
    final_cassette_promoter,
    final_cassette_conditional,
    final_cassette_resistance,
    final_backbone_name,
    final_well_assay_complete,
    final_well_accepted,
    final_pick_plate_name,
    final_pick_plate_id,
    final_pick_well_name,
    final_pick_well_id,
    final_pick_well_created_ts,
    final_pick_recombinase_id,
    final_pick_qc_seq_pass,
    final_pick_cassette_name,
    final_pick_cassette_cre,
    final_pick_cassette_promoter,
    final_pick_cassette_conditional,
    final_pick_cassette_resistance,
    final_pick_backbone_name,
    final_pick_well_assay_complete,
    final_pick_well_accepted,   
    dna_plate_name,
    dna_plate_id,
    dna_well_name,
    dna_well_id,
    dna_well_created_ts,
    dna_qc_seq_pass,
    dna_status_pass,
    dna_quality,
    dna_quality_comment,
    dna_well_assay_complete,
    dna_well_accepted,
--New ASSEMBLY well info
    assembly_well_id,
    assembly_well_name,
    assembly_plate_id,
    assembly_plate_name,
    assembly_well_assay_complete,
    assembly_well_created_ts,
    assembly_well_accepted,
    assembly_well_left_crispr_well_id,
    assembly_well_right_crispr_well_id,
--New CRISPR_EP well info
    crispr_ep_well_id,
    crispr_ep_well_name,
    crispr_ep_plate_id,
    crispr_ep_plate_name,
    crispr_ep_well_assay_complete,
    crispr_ep_well_created_ts,
    crispr_ep_well_accepted,
    crispr_ep_well_nuclease,
    crispr_ep_well_cell_line,
--
    ep_plate_name,
    ep_plate_id,
    ep_well_name,
    ep_well_id,
    ep_well_created_ts,
    ep_well_recombinase_id,
    ep_first_cell_line_name,
    ep_colonies_picked,
    ep_colonies_total,
    ep_colonies_rem_unstained,
    ep_well_assay_complete,
    ep_well_accepted,
    ep_pick_plate_name,
    ep_pick_plate_id,
    ep_pick_well_name,
    ep_pick_well_id,
    ep_pick_well_created_ts,
    ep_pick_well_recombinase_id,
    ep_pick_qc_seq_pass,
    ep_pick_well_assay_complete,
    ep_pick_well_accepted,
    xep_plate_name,
    xep_plate_id,
    xep_well_name,
    xep_well_id,
    xep_well_created_ts,
    xep_well_recombinase_id,
    xep_qc_seq_pass,
    xep_well_assay_complete,
    xep_well_accepted,
    sep_plate_name,
    sep_plate_id,
    sep_well_name,
    sep_well_id,
    sep_well_created_ts,
    sep_well_recombinase_id,
    sep_well_assay_complete,
    sep_well_accepted,
    sep_pick_plate_name,
    sep_pick_plate_id,
    sep_pick_well_name,
    sep_pick_well_id,
    sep_pick_well_created_ts,
    sep_pick_well_recombinase_id,
    sep_pick_qc_seq_pass,
    sep_pick_well_assay_complete,
    sep_pick_well_accepted,
    fp_plate_name,
    fp_plate_id,
    fp_well_name,
    fp_well_id,
    fp_well_created_ts,
    fp_well_assay_complete,
    fp_well_accepted,
    piq_plate_name,
    piq_plate_id,
    piq_well_name,
    piq_well_id,
    piq_well_created_ts,
    piq_well_assay_complete,
    piq_well_accepted,
    sfp_plate_name,
    sfp_plate_id,
    sfp_well_name,
    sfp_well_id,
    sfp_well_created_ts,
    sfp_well_assay_complete,
    sfp_well_accepted
    )
SELECT 
    insert_timestamp,
    design_id,
    design_name,
    design_type,
    design_species_id,
    design_gene_id,
    design_gene_symbol,
    design_bacs,
    design_phase,
    design_plate_name,
    design_plate_id,
    design_well_name,
    design_well_id,
    design_well_created_ts,
    design_well_assay_complete,
    design_well_accepted,
    int_plate_name,
    int_plate_id,
    int_well_name,
    int_well_id,
    int_well_created_ts,
    int_recombinase_id,
    int_qc_seq_pass,
    int_cassette_name,
    int_cassette_cre,
    int_cassette_promoter,
    int_cassette_conditional,
    int_cassette_resistance,
    int_backbone_name,
    int_well_assay_complete,
    int_well_accepted,
    final_plate_name,
    final_plate_id,
    final_well_name,
    final_well_id,
    final_well_created_ts,
    final_recombinase_id,
    final_qc_seq_pass,
    final_cassette_name,
    final_cassette_cre,
    final_cassette_promoter,
    final_cassette_conditional,
    final_cassette_resistance,
    final_backbone_name,
    final_well_assay_complete,
    final_well_accepted,
    final_pick_plate_name,
    final_pick_plate_id,
    final_pick_well_name,
    final_pick_well_id,
    final_pick_well_created_ts,
    final_pick_recombinase_id,
    final_pick_qc_seq_pass,
    final_pick_cassette_name,
    final_pick_cassette_cre,
    final_pick_cassette_promoter,
    final_pick_cassette_conditional,
    final_pick_cassette_resistance,
    final_pick_backbone_name,
    final_pick_well_assay_complete,
    final_pick_well_accepted,   
    dna_plate_name,
    dna_plate_id,
    dna_well_name,
    dna_well_id,
    dna_well_created_ts,
    dna_qc_seq_pass,
    dna_status_pass,
    dna_quality,
    dna_quality_comment,
    dna_well_assay_complete,
    dna_well_accepted,
--New ASSEMBLY well info
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
--New CRISPR_EP well info
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
--
    ep_plate_name,
    ep_plate_id,
    ep_well_name,
    ep_well_id,
    ep_well_created_ts,
    ep_well_recombinase_id,
    ep_first_cell_line_name,
    ep_colonies_picked,
    ep_colonies_total,
    ep_colonies_rem_unstained,
    ep_well_assay_complete,
    ep_well_accepted,
    ep_pick_plate_name,
    ep_pick_plate_id,
    ep_pick_well_name,
    ep_pick_well_id,
    ep_pick_well_created_ts,
    ep_pick_well_recombinase_id,
    ep_pick_qc_seq_pass,
    ep_pick_well_assay_complete,
    ep_pick_well_accepted,
    xep_plate_name,
    xep_plate_id,
    xep_well_name,
    xep_well_id,
    xep_well_created_ts,
    xep_well_recombinase_id,
    xep_qc_seq_pass,
    xep_well_assay_complete,
    xep_well_accepted,
    sep_plate_name,
    sep_plate_id,
    sep_well_name,
    sep_well_id,
    sep_well_created_ts,
    sep_well_recombinase_id,
    sep_well_assay_complete,
    sep_well_accepted,
    sep_pick_plate_name,
    sep_pick_plate_id,
    sep_pick_well_name,
    sep_pick_well_id,
    sep_pick_well_created_ts,
    sep_pick_well_recombinase_id,
    sep_pick_qc_seq_pass,
    sep_pick_well_assay_complete,
    sep_pick_well_accepted,
    fp_plate_name,
    fp_plate_id,
    fp_well_name,
    fp_well_id,
    fp_well_created_ts,
    fp_well_assay_complete,
    fp_well_accepted,
    piq_plate_name,
    piq_plate_id,
    piq_well_name,
    piq_well_id,
    piq_well_created_ts,
    piq_well_assay_complete,
    piq_well_accepted,
    sfp_plate_name,
    sfp_plate_id,
    sfp_well_name,
    sfp_well_id,
    sfp_well_created_ts,
    sfp_well_assay_complete,
    sfp_well_accepted
FROM public.summaries_old;

-- Drop the old version of the table (this takes the sequence with it)
DROP TABLE public.summaries_old CASCADE;
