DROP TABLE IF EXISTS public.summaries;

CREATE TABLE public.summaries (
--"DESIGN: design_gene_id,design_gene_symbol,design_bacs,design_plate_name,design_plate_id,design_well_name,design_well_id,design_well_created_ts,design_type,design_phase,design_name,design_id,design_well_assay_complete,design_well_accepted,"
	design_gene_id text,
	design_gene_symbol text,
	design_bacs text,
	design_plate_name text,
	design_plate_id integer,
	design_well_name text,
	design_well_id integer,
	design_well_created_ts timestamp without time zone,
	design_type text,
	design_phase integer,
	design_name text,
	design_id integer,
	design_well_assay_complete timestamp without time zone,
	design_well_accepted boolean,
--"INT: int_plate_name,int_plate_id,int_well_name,int_well_id,int_well_created_ts,int_qc_seq_pass,int_cassette,int_backbone,int_well_assay_complete,int_well_accepted,"
	int_plate_name text,
	int_plate_id integer,
	int_well_name text,
	int_well_id integer,
	int_well_created_ts timestamp without time zone,
	int_qc_seq_pass boolean,
	int_cassette_name text,
	int_backbone_name text,
	int_well_assay_complete timestamp without time zone,
	int_well_accepted boolean,
--"FINAL: final_plate_name,final_plate_id,final_well_name,final_well_id,final_well_created_ts,final_recombinase,final_qc_seq_pass,final_cassette,final_backbone,final_well_assay_complete,final_well_accepted,"
	final_plate_name text,
	final_plate_id integer,
	final_well_name name,
	final_well_id integer,
	final_well_created_ts timestamp without time zone,
	final_recombinase_id text,
	final_qc_seq_pass boolean,
	final_cassette_name text,
	final_cassette_cre boolean,
	final_cassette_promoter boolean,
	final_cassette_conditional boolean,
	final_backbone_name text,
	final_well_assay_complete timestamp without time zone,
	final_well_accepted boolean,
--"FINAL_PICK: final_pick_plate_name,final_pick_plate_id,final_pick_well_name,final_pick_well_id,final_pick_well_created_ts,final_pick_recombinase,final_pick_qc_seq_pass,final_pick_cassette,final_pick_backbone,final_pick_well_assay_complete,final_pick_well_accepted,"
	final_pick_plate_name text,
	final_pick_plate_id integer,
	final_pick_well_name name,
	final_pick_well_id integer,
	final_pick_well_created_ts timestamp without time zone,
	final_pick_recombinase_id text,
	final_pick_qc_seq_pass boolean,
	final_pick_cassette_name text,
	final_pick_cassette_cre boolean,
	final_pick_cassette_promoter boolean,
	final_pick_cassette_conditional boolean,
	final_pick_backbone_name text,
	final_pick_well_assay_complete timestamp without time zone,
	final_pick_well_accepted boolean,
--"DNA: dna_plate_name,dna_plate_id,dna_well_name,dna_well_id,dna_well_created_ts,dna_qc_seq_pass,dna_status_pass,dna_quality,dna_well_assay_complete,dna_well_accepted,"
	dna_plate_name text,
	dna_plate_id integer,
	dna_well_name text,
	dna_well_id integer,
	dna_well_created_ts timestamp without time zone,
	dna_qc_seq_pass boolean,
	dna_status_pass boolean,
	dna_quality text,
	dna_well_assay_complete timestamp without time zone,
	dna_well_accepted boolean,
--"EP: ep_plate_name,ep_plate_id,ep_well_name,ep_well_id,ep_well_created_ts,ep_first_cell_line,ep_colonies_picked,ep_colonies_total,ep_colonies_rem_unstained,ep_well_assay_complete,ep_well_accepted,
	ep_plate_name text,
	ep_plate_id integer,
	ep_well_name text,
	ep_well_id integer,
	ep_well_created_ts timestamp without time zone,
	ep_first_cell_line_name text,
	ep_colonies_picked integer,
	ep_colonies_total integer,
	ep_colonies_rem_unstained integer,
	ep_well_assay_complete timestamp without time zone,
	ep_well_accepted boolean,
--"EP_PICK: ep_pick_plate_name,ep_pick_plate_id,ep_pick_well_name,ep_pick_well_id,ep_pick_well_created_ts,ep_pick_qc_seq_pass,ep_pick_well_assay_complete,ep_pick_well_accepted,"
	ep_pick_plate_name text,
	ep_pick_plate_id integer,
	ep_pick_well_name text,
	ep_pick_well_id integer,
	ep_pick_well_created_ts timestamp without time zone,
	ep_pick_qc_seq_pass boolean,
	ep_pick_well_assay_complete timestamp without time zone,
	ep_pick_well_accepted boolean,
--"SEP: sep_plate_name,sep_plate_id,sep_well_name,sep_well_id,sep_well_created_ts,sep_second_cell_line,sep_well_assay_complete,sep_well_accepted,"
	sep_plate_name text,
	sep_plate_id integer,
	sep_well_name text,
	sep_well_id integer,
	sep_well_created_ts timestamp without time zone,
	sep_second_cell_line_name text,
	sep_well_assay_complete timestamp without time zone,
	sep_well_accepted boolean,
--"SEP_PICK: sep_pick_plate_name,sep_pick_plate_id,sep_pick_well_name,sep_pick_well_id,sep_pick_well_created_ts,sep_pick_qc_seq_pass,sep_pick_well_assay_complete,sep_pick_well_accepted,
	sep_pick_plate_name text,
	sep_pick_plate_id integer,
	sep_pick_well_name text,
	sep_pick_well_id integer,
	sep_pick_well_created_ts timestamp without time zone,
	sep_pick_qc_seq_pass boolean,
	sep_pick_well_assay_complete timestamp without time zone,
	sep_pick_well_accepted boolean,
--"FP: fp_plate_name,fp_plate_id,fp_well_name,fp_well_id,fp_well_created_ts,fp_well_assay_complete,fp_well_accepted
	fp_plate_name text,
	fp_plate_id integer,
	fp_well_name text,
	fp_well_id integer,
	fp_well_created_ts timestamp without time zone,
	fp_well_assay_complete timestamp without time zone,
	fp_well_accepted boolean,
--"SFP: sfp_plate_name,sfp_plate_id,sfp_well_name,sfp_well_id,sfp_well_created_ts,sfp_well_assay_complete,sfp_well_accepted,
	sfp_plate_name text,
	sfp_plate_id integer,
	sfp_well_name text,
	sfp_well_id integer,
	sfp_well_created_ts timestamp without time zone,
	sfp_well_assay_complete timestamp without time zone,
	sfp_well_accepted boolean

);

GRANT SELECT ON summaries TO "[% ro_role %]";
GRANT SELECT, INSERT, UPDATE, DELETE ON summaries TO "[% rw_role %]";
